# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#This is an automatically generated file. Do not edit!

LOCAL_PATH := vendor/htc/htc_a5dwg/proprietary

PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/bin/time_daemon:system/bin/time_daemon \
    $(LOCAL_PATH)/bin/mpdecision:system/bin/mpdecision \
    $(LOCAL_PATH)/bin/thermal-engine:system/bin/thermal-engine \
    $(LOCAL_PATH)/bin/hcheck:system/bin/hcheck \
    $(LOCAL_PATH)/bin/netmgrd:system/bin/netmgrd \
    $(LOCAL_PATH)/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    $(LOCAL_PATH)/bin/adsprpcd:system/bin/adsprpcd \
    $(LOCAL_PATH)/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    $(LOCAL_PATH)/bin/rmt_storage:system/bin/rmt_storage \
    $(LOCAL_PATH)/bin/irsc_util:system/bin/irsc_util \
    $(LOCAL_PATH)/bin/mm-qcamera-app:system/bin/mm-qcamera-app \
    $(LOCAL_PATH)/bin/ptt_socket_app:system/bin/ptt_socket_app \
    $(LOCAL_PATH)/bin/qmuxd:system/bin/qmuxd \
    $(LOCAL_PATH)/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
    $(LOCAL_PATH)/lib/libgps.utils.so:system/lib/libgps.utils.so \
    $(LOCAL_PATH)/lib/libawb_calibration.so:system/lib/libawb_calibration.so \
    $(LOCAL_PATH)/lib/libtuning_aec_ov13850_video_60fps.so:system/lib/libtuning_aec_ov13850_video_60fps.so \
    $(LOCAL_PATH)/lib/libtuning_awb_s5k5e_onelane.so:system/lib/libtuning_awb_s5k5e_onelane.so \
    $(LOCAL_PATH)/lib/libtuning_aec_ov13850_zsl.so:system/lib/libtuning_aec_ov13850_zsl.so \
    $(LOCAL_PATH)/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    $(LOCAL_PATH)/lib/libtuning_aec_ov13850_night_16_9.so:system/lib/libtuning_aec_ov13850_night_16_9.so \
    $(LOCAL_PATH)/lib/libcamera_af.so:system/lib/libcamera_af.so \
    $(LOCAL_PATH)/lib/libalDynamicWarping_SDW_TWO.so:system/lib/libalDynamicWarping_SDW_TWO.so \
    $(LOCAL_PATH)/lib/libtuning_aec_s5k5e_onelane_zsl.so:system/lib/libtuning_aec_s5k5e_onelane_zsl.so \
    $(LOCAL_PATH)/lib/libalDE_SDE_TWO.so:system/lib/libalDE_SDE_TWO.so \
    $(LOCAL_PATH)/lib/libcamerapp.so:system/lib/libcamerapp.so \
    $(LOCAL_PATH)/lib/libalDE.so:system/lib/libalDE.so \
    $(LOCAL_PATH)/lib/libtuning_af_1.so:system/lib/libtuning_af_1.so \
    $(LOCAL_PATH)/lib/libcamera_metadata.so:system/lib/libcamera_metadata.so \
    $(LOCAL_PATH)/lib/libcamera_aec.so:system/lib/libcamera_aec.so \
    $(LOCAL_PATH)/lib/libtuning_aec_s5k5e_onelane_zsl_16_9.so:system/lib/libtuning_aec_s5k5e_onelane_zsl_16_9.so \
    $(LOCAL_PATH)/lib/libtuning_aec_s5k5e_onelane_video_16_9.so:system/lib/libtuning_aec_s5k5e_onelane_video_16_9.so \
    $(LOCAL_PATH)/lib/libtuning_aec_ov13850_hdr.so:system/lib/libtuning_aec_ov13850_hdr.so \
    $(LOCAL_PATH)/lib/libtuning_aec.so:system/lib/libtuning_aec.so \
    $(LOCAL_PATH)/lib/libqomx_core.so:system/lib/libqomx_core.so \
    $(LOCAL_PATH)/lib/libtuning_af_0.so:system/lib/libtuning_af_0.so \
    $(LOCAL_PATH)/lib/libtuning_aec_ov13850_zoe.so:system/lib/libtuning_aec_ov13850_zoe.so \
    $(LOCAL_PATH)/lib/libtuning_aec_ov13850_video.so:system/lib/libtuning_aec_ov13850_video.so \
    $(LOCAL_PATH)/lib/hw/camera.msm8226.so:system/lib/hw/camera.msm8226.so \
    $(LOCAL_PATH)/lib/hw/sensors.msm8226.so:system/lib/hw/sensors.msm8226.so \
    $(LOCAL_PATH)/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    $(LOCAL_PATH)/lib/libtuning_aec_s5k5e_onelane_hdr.so:system/lib/libtuning_aec_s5k5e_onelane_hdr.so \
    $(LOCAL_PATH)/lib/libtuning_aec_ov13850_night.so:system/lib/libtuning_aec_ov13850_night.so \
    $(LOCAL_PATH)/lib/libtuning_aec_ov13850_zsl_16_9.so:system/lib/libtuning_aec_ov13850_zsl_16_9.so \
    $(LOCAL_PATH)/lib/libhtccamera.so:system/lib/libhtccamera.so \
    $(LOCAL_PATH)/lib/modules/msm-buspm-dev.ko:system/lib/modules/msm-buspm-dev.ko \
    $(LOCAL_PATH)/lib/modules/moc_crypto.ko.3.4.10:system/lib/modules/moc_crypto.ko.3.4.10 \
    $(LOCAL_PATH)/lib/modules/radio-iris-transport.ko:system/lib/modules/radio-iris-transport.ko \
    $(LOCAL_PATH)/lib/modules/qcrypto.ko:system/lib/modules/qcrypto.ko \
    $(LOCAL_PATH)/lib/modules/ecryptfs.ko:system/lib/modules/ecryptfs.ko \
    $(LOCAL_PATH)/lib/modules/moc_crypto.ko.sig.3.4.10:system/lib/modules/moc_crypto.ko.sig.3.4.10 \
    $(LOCAL_PATH)/lib/modules/dma_test.ko:system/lib/modules/dma_test.ko \
    $(LOCAL_PATH)/lib/modules/mmc_test.ko:system/lib/modules/mmc_test.ko \
    $(LOCAL_PATH)/lib/modules/mckernelapi.ko:system/lib/modules/mckernelapi.ko \
    $(LOCAL_PATH)/lib/modules/mcdrvmodule.ko:system/lib/modules/mcdrvmodule.ko \
    $(LOCAL_PATH)/lib/modules/reset_modem.ko:system/lib/modules/reset_modem.ko \
    $(LOCAL_PATH)/lib/modules/evbug.ko:system/lib/modules/evbug.ko \
    $(LOCAL_PATH)/lib/modules/adsprpc.ko:system/lib/modules/adsprpc.ko \
    $(LOCAL_PATH)/lib/modules/texfat.ko:system/lib/modules/texfat.ko \
    $(LOCAL_PATH)/lib/modules/spidev.ko:system/lib/modules/spidev.ko \
    $(LOCAL_PATH)/lib/modules/scsi_wait_scan.ko:system/lib/modules/scsi_wait_scan.ko \
    $(LOCAL_PATH)/lib/modules/qcedev.ko:system/lib/modules/qcedev.ko \
    $(LOCAL_PATH)/lib/modules/dm-crypt.ko:system/lib/modules/dm-crypt.ko \
    $(LOCAL_PATH)/lib/modules/moc_platform_mod.ko.3.4.10:system/lib/modules/moc_platform_mod.ko.3.4.10 \
    $(LOCAL_PATH)/lib/modules/ansi_cprng.ko:system/lib/modules/ansi_cprng.ko \
    $(LOCAL_PATH)/lib/modules/gspca_main.ko:system/lib/modules/gspca_main.ko \
    $(LOCAL_PATH)/lib/modules/wp_mod.ko:system/lib/modules/wp_mod.ko \
    $(LOCAL_PATH)/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    $(LOCAL_PATH)/lib/libtuning_awb_ov13850.so:system/lib/libtuning_awb_ov13850.so \
    $(LOCAL_PATH)/lib/libtuning_aec_s5k5e_onelane_hdr_16_9.so:system/lib/libtuning_aec_s5k5e_onelane_hdr_16_9.so \
    $(LOCAL_PATH)/lib/libtuning_aec_ov13850_hdr_16_9.so:system/lib/libtuning_aec_ov13850_hdr_16_9.so \
    $(LOCAL_PATH)/lib/libtuning_af.so:system/lib/libtuning_af.so \
    $(LOCAL_PATH)/lib/libtuning_af_3.so:system/lib/libtuning_af_3.so \
    $(LOCAL_PATH)/lib/libtuning_aec_ov13850_videoHFR.so:system/lib/libtuning_aec_ov13850_videoHFR.so \
    $(LOCAL_PATH)/lib/libcamera_awb.so:system/lib/libcamera_awb.so \
    $(LOCAL_PATH)/lib/libtuning_aec_s5k5e_onelane_video.so:system/lib/libtuning_aec_s5k5e_onelane_video.so \
    $(LOCAL_PATH)/vendor/firmware/keymaster.b01:system/vendor/firmware/keymaster.b01 \
    $(LOCAL_PATH)/vendor/firmware/keymaster.b00:system/vendor/firmware/keymaster.b00 \
    $(LOCAL_PATH)/vendor/firmware/keymaster.b03:system/vendor/firmware/keymaster.b03 \
    $(LOCAL_PATH)/vendor/firmware/keymaster.b02:system/vendor/firmware/keymaster.b02 \
    $(LOCAL_PATH)/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    $(LOCAL_PATH)/vendor/lib/rfsa/adsp/libfastcvadsp.so:system/vendor/lib/rfsa/adsp/libfastcvadsp.so \
    $(LOCAL_PATH)/vendor/lib/rfsa/adsp/libdspCV_skel.so:system/vendor/lib/rfsa/adsp/libdspCV_skel.so \
    $(LOCAL_PATH)/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so:system/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so \
    $(LOCAL_PATH)/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    $(LOCAL_PATH)/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    $(LOCAL_PATH)/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
    $(LOCAL_PATH)/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera_SKUAA_ST_gc0339.so:system/vendor/lib/libmmcamera_SKUAA_ST_gc0339.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera_s5k5e_onelane.so:system/vendor/lib/libmmcamera_s5k5e_onelane.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera_SKUAB_ST_s5k4e1.so:system/vendor/lib/libmmcamera_SKUAB_ST_s5k4e1.so \
    $(LOCAL_PATH)/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    $(LOCAL_PATH)/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    $(LOCAL_PATH)/vendor/lib/libchromatix_ov13850_hfr.so:system/vendor/lib/libchromatix_ov13850_hfr.so \
    $(LOCAL_PATH)/vendor/lib/libacdbmapper.so:system/vendor/lib/libacdbmapper.so \
    $(LOCAL_PATH)/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    $(LOCAL_PATH)/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    $(LOCAL_PATH)/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    $(LOCAL_PATH)/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    $(LOCAL_PATH)/vendor/lib/libchromatix_ov13850_default_video.so:system/vendor/lib/libchromatix_ov13850_default_video.so \
    $(LOCAL_PATH)/vendor/lib/libfastcvadsp_stub.so:system/vendor/lib/libfastcvadsp_stub.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    $(LOCAL_PATH)/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    $(LOCAL_PATH)/vendor/lib/libchromatix_ov13850_preview.so:system/vendor/lib/libchromatix_ov13850_preview.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera_ov5648_oty5f03.so:system/vendor/lib/libmmcamera_ov5648_oty5f03.so \
    $(LOCAL_PATH)/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
    $(LOCAL_PATH)/vendor/lib/libOpenVG.so:system/vendor/lib/libOpenVG.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    $(LOCAL_PATH)/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    $(LOCAL_PATH)/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    $(LOCAL_PATH)/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so:system/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so \
    $(LOCAL_PATH)/vendor/lib/libchromatix_ov13850_hdr.so:system/vendor/lib/libchromatix_ov13850_hdr.so \
    $(LOCAL_PATH)/vendor/lib/libchromatix_ov8865_q8v18a_preview.so:system/vendor/lib/libchromatix_ov8865_q8v18a_preview.so \
    $(LOCAL_PATH)/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    $(LOCAL_PATH)/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    $(LOCAL_PATH)/vendor/lib/libchromatix_ov5648_oty5f03_default_video.so:system/vendor/lib/libchromatix_ov5648_oty5f03_default_video.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so:system/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so \
    $(LOCAL_PATH)/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    $(LOCAL_PATH)/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    $(LOCAL_PATH)/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    $(LOCAL_PATH)/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    $(LOCAL_PATH)/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    $(LOCAL_PATH)/vendor/lib/libchromatix_ov8865_q8v18a_video_hd.so:system/vendor/lib/libchromatix_ov8865_q8v18a_video_hd.so \
    $(LOCAL_PATH)/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    $(LOCAL_PATH)/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    $(LOCAL_PATH)/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    $(LOCAL_PATH)/vendor/lib/libchromatix_ov8865_q8v18a_default_video.so:system/vendor/lib/libchromatix_ov8865_q8v18a_default_video.so \
    $(LOCAL_PATH)/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    $(LOCAL_PATH)/vendor/lib/libc2d30.so:system/vendor/lib/libc2d30.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    $(LOCAL_PATH)/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    $(LOCAL_PATH)/vendor/lib/libchromatix_ov8865_q8v18a_hfr_90fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_90fps.so \
    $(LOCAL_PATH)/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera_skuf_ov12830_p12v01c.so:system/vendor/lib/libmmcamera_skuf_ov12830_p12v01c.so \
    $(LOCAL_PATH)/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    $(LOCAL_PATH)/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    $(LOCAL_PATH)/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    $(LOCAL_PATH)/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    $(LOCAL_PATH)/vendor/lib/libdsnetutils.so:system/vendor/lib/libdsnetutils.so \
    $(LOCAL_PATH)/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    $(LOCAL_PATH)/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    $(LOCAL_PATH)/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    $(LOCAL_PATH)/vendor/lib/libchromatix_ov8865_q8v18a_common.so:system/vendor/lib/libchromatix_ov8865_q8v18a_common.so \
    $(LOCAL_PATH)/vendor/lib/libc2d2_z180.so:system/vendor/lib/libc2d2_z180.so \
    $(LOCAL_PATH)/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so:system/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so \
    $(LOCAL_PATH)/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera_ov13850.so:system/vendor/lib/libmmcamera_ov13850.so \
    $(LOCAL_PATH)/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    $(LOCAL_PATH)/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    $(LOCAL_PATH)/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    $(LOCAL_PATH)/vendor/lib/libchromatix_ov13850_common.so:system/vendor/lib/libchromatix_ov13850_common.so \
    $(LOCAL_PATH)/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    $(LOCAL_PATH)/vendor/lib/libqc-opt.so:system/vendor/lib/libqc-opt.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    $(LOCAL_PATH)/vendor/lib/libchromatix_ov13850_hfr_60fps.so:system/vendor/lib/libchromatix_ov13850_hfr_60fps.so \
    $(LOCAL_PATH)/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    $(LOCAL_PATH)/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera_skuf_ov5648_p5v23c.so:system/vendor/lib/libmmcamera_skuf_ov5648_p5v23c.so \
    $(LOCAL_PATH)/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
    $(LOCAL_PATH)/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    $(LOCAL_PATH)/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    $(LOCAL_PATH)/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so:system/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera_truly_cm7700_eeprom.so:system/vendor/lib/libmmcamera_truly_cm7700_eeprom.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera_sp1628.so:system/vendor/lib/libmmcamera_sp1628.so \
    $(LOCAL_PATH)/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    $(LOCAL_PATH)/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    $(LOCAL_PATH)/vendor/lib/libchromatix_ov5648_oty5f03_common.so:system/vendor/lib/libchromatix_ov5648_oty5f03_common.so \
    $(LOCAL_PATH)/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    $(LOCAL_PATH)/vendor/lib/libscve.so:system/vendor/lib/libscve.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    $(LOCAL_PATH)/vendor/lib/libchromatix_ov8865_q8v18a_hfr_60fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_60fps.so \
    $(LOCAL_PATH)/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    $(LOCAL_PATH)/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    $(LOCAL_PATH)/vendor/lib/libchromatix_ov5648_oty5f03_preview.so:system/vendor/lib/libchromatix_ov5648_oty5f03_preview.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera_ov8865_q8v18a.so:system/vendor/lib/libmmcamera_ov8865_q8v18a.so \
    $(LOCAL_PATH)/vendor/lib/libchromatix_ov8865_q8v18a_zsl.so:system/vendor/lib/libchromatix_ov8865_q8v18a_zsl.so \
    $(LOCAL_PATH)/vendor/lib/libchromatix_ov8865_q8v18a_hfr_120fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_120fps.so \
    $(LOCAL_PATH)/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    $(LOCAL_PATH)/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    $(LOCAL_PATH)/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    $(LOCAL_PATH)/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    $(LOCAL_PATH)/etc/Global_cal.acdb:system/etc/Global_cal.acdb \
    $(LOCAL_PATH)/etc/tfa/playbackwoofer_l.preset:system/etc/tfa/playbackwoofer_l.preset \
    $(LOCAL_PATH)/etc/tfa/voiceWB_l.eq:system/etc/tfa/voiceWB_l.eq \
    $(LOCAL_PATH)/etc/tfa/playbackMFG.eq:system/etc/tfa/playbackMFG.eq \
    $(LOCAL_PATH)/etc/tfa/playbackwoofer.preset:system/etc/tfa/playbackwoofer.preset \
    $(LOCAL_PATH)/etc/tfa/voip_l.drc:system/etc/tfa/voip_l.drc \
    $(LOCAL_PATH)/etc/tfa/Rec_Video_l.preset:system/etc/tfa/Rec_Video_l.preset \
    $(LOCAL_PATH)/etc/tfa/playbackwoofer.eq:system/etc/tfa/playbackwoofer.eq \
    $(LOCAL_PATH)/etc/tfa/playbackMFG_l.eq:system/etc/tfa/playbackMFG_l.eq \
    $(LOCAL_PATH)/etc/tfa/fm.preset:system/etc/tfa/fm.preset \
    $(LOCAL_PATH)/etc/tfa/playback_l.preset:system/etc/tfa/playback_l.preset \
    $(LOCAL_PATH)/etc/tfa/playbackMFG_l.drc:system/etc/tfa/playbackMFG_l.drc \
    $(LOCAL_PATH)/etc/tfa/voip.eq:system/etc/tfa/voip.eq \
    $(LOCAL_PATH)/etc/tfa/voip_l.preset:system/etc/tfa/voip_l.preset \
    $(LOCAL_PATH)/etc/tfa/Rec_Video_l.drc:system/etc/tfa/Rec_Video_l.drc \
    $(LOCAL_PATH)/etc/tfa/tfa9895.speaker:system/etc/tfa/tfa9895.speaker \
    $(LOCAL_PATH)/etc/tfa/voice.drc:system/etc/tfa/voice.drc \
    $(LOCAL_PATH)/etc/tfa/playbackwoofer.drc:system/etc/tfa/playbackwoofer.drc \
    $(LOCAL_PATH)/etc/tfa/voice.eq:system/etc/tfa/voice.eq \
    $(LOCAL_PATH)/etc/tfa/voice.preset:system/etc/tfa/voice.preset \
    $(LOCAL_PATH)/etc/tfa/tfa9895_l.speaker:system/etc/tfa/tfa9895_l.speaker \
    $(LOCAL_PATH)/etc/tfa/playback_l.eq:system/etc/tfa/playback_l.eq \
    $(LOCAL_PATH)/etc/tfa/fm.eq:system/etc/tfa/fm.eq \
    $(LOCAL_PATH)/etc/tfa/Rec_Video.eq:system/etc/tfa/Rec_Video.eq \
    $(LOCAL_PATH)/etc/tfa/fm_l.drc:system/etc/tfa/fm_l.drc \
    $(LOCAL_PATH)/etc/tfa/voip.preset:system/etc/tfa/voip.preset \
    $(LOCAL_PATH)/etc/tfa/playbackMFG.config:system/etc/tfa/playbackMFG.config \
    $(LOCAL_PATH)/etc/tfa/fm.drc:system/etc/tfa/fm.drc \
    $(LOCAL_PATH)/etc/tfa/playbackMFG_l.config:system/etc/tfa/playbackMFG_l.config \
    $(LOCAL_PATH)/etc/tfa/playback.drc:system/etc/tfa/playback.drc \
    $(LOCAL_PATH)/etc/tfa/voice_l.eq:system/etc/tfa/voice_l.eq \
    $(LOCAL_PATH)/etc/tfa/playbackwoofer_l.drc:system/etc/tfa/playbackwoofer_l.drc \
    $(LOCAL_PATH)/etc/tfa/playback.preset:system/etc/tfa/playback.preset \
    $(LOCAL_PATH)/etc/tfa/voice_l.drc:system/etc/tfa/voice_l.drc \
    $(LOCAL_PATH)/etc/tfa/voip_l.eq:system/etc/tfa/voip_l.eq \
    $(LOCAL_PATH)/etc/tfa/fm_l.eq:system/etc/tfa/fm_l.eq \
    $(LOCAL_PATH)/etc/tfa/Rec_Video_l.eq:system/etc/tfa/Rec_Video_l.eq \
    $(LOCAL_PATH)/etc/tfa/playbackMFG.drc:system/etc/tfa/playbackMFG.drc \
    $(LOCAL_PATH)/etc/tfa/Rec_Video.drc:system/etc/tfa/Rec_Video.drc \
    $(LOCAL_PATH)/etc/tfa/playback.eq:system/etc/tfa/playback.eq \
    $(LOCAL_PATH)/etc/tfa/playbackMFG.preset:system/etc/tfa/playbackMFG.preset \
    $(LOCAL_PATH)/etc/tfa/voiceWB.eq:system/etc/tfa/voiceWB.eq \
    $(LOCAL_PATH)/etc/tfa/Rec_Video.preset:system/etc/tfa/Rec_Video.preset \
    $(LOCAL_PATH)/etc/tfa/voip.drc:system/etc/tfa/voip.drc \
    $(LOCAL_PATH)/etc/tfa/fm_l.preset:system/etc/tfa/fm_l.preset \
    $(LOCAL_PATH)/etc/tfa/tfa9895.config:system/etc/tfa/tfa9895.config \
    $(LOCAL_PATH)/etc/tfa/playbackMFG_l.preset:system/etc/tfa/playbackMFG_l.preset \
    $(LOCAL_PATH)/etc/tfa/playbackwoofer_l.eq:system/etc/tfa/playbackwoofer_l.eq \
    $(LOCAL_PATH)/etc/tfa/voice_l.preset:system/etc/tfa/voice_l.preset \
    $(LOCAL_PATH)/etc/tfa/playback_l.drc:system/etc/tfa/playback_l.drc \
    $(LOCAL_PATH)/etc/Bluetooth_cal.acdb:system/etc/Bluetooth_cal.acdb \
    $(LOCAL_PATH)/etc/firmware/widevine.b01:system/etc/firmware/widevine.b01 \
    $(LOCAL_PATH)/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    $(LOCAL_PATH)/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    $(LOCAL_PATH)/etc/firmware/hcheck.b01:system/etc/firmware/hcheck.b01 \
    $(LOCAL_PATH)/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
    $(LOCAL_PATH)/etc/firmware/widevine.b03:system/etc/firmware/widevine.b03 \
    $(LOCAL_PATH)/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    $(LOCAL_PATH)/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    $(LOCAL_PATH)/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    $(LOCAL_PATH)/etc/firmware/widevine.b02:system/etc/firmware/widevine.b02 \
    $(LOCAL_PATH)/etc/firmware/ILP0100_IPM_Code_out.bin:system/etc/firmware/ILP0100_IPM_Code_out.bin \
    $(LOCAL_PATH)/etc/firmware/hcheck.b03:system/etc/firmware/hcheck.b03 \
    $(LOCAL_PATH)/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    $(LOCAL_PATH)/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    $(LOCAL_PATH)/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    $(LOCAL_PATH)/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    $(LOCAL_PATH)/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    $(LOCAL_PATH)/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    $(LOCAL_PATH)/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    $(LOCAL_PATH)/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
    $(LOCAL_PATH)/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    $(LOCAL_PATH)/etc/firmware/hcheck.b00:system/etc/firmware/hcheck.b00 \
    $(LOCAL_PATH)/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    $(LOCAL_PATH)/etc/firmware/hcheck.b02:system/etc/firmware/hcheck.b02 \
    $(LOCAL_PATH)/etc/firmware/ILP0100_IPM_Data_out.bin:system/etc/firmware/ILP0100_IPM_Data_out.bin \
    $(LOCAL_PATH)/etc/firmware/lscbuffer_rev2.bin:system/etc/firmware/lscbuffer_rev2.bin \
    $(LOCAL_PATH)/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    $(LOCAL_PATH)/etc/firmware/widevine.b00:system/etc/firmware/widevine.b00 \
    $(LOCAL_PATH)/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    $(LOCAL_PATH)/etc/sound_mfg.txt:system/etc/sound_mfg.txt \
    $(LOCAL_PATH)/etc/hldm.bin:system/etc/hldm.bin \
    $(LOCAL_PATH)/etc/sound_mfg_DMIC.txt:system/etc/sound_mfg_DMIC.txt \
    $(LOCAL_PATH)/etc/Speaker_cal.acdb:system/etc/Speaker_cal.acdb \
    $(LOCAL_PATH)/etc/Headset_cal.acdb:system/etc/Headset_cal.acdb \
    $(LOCAL_PATH)/etc/Hdmi_cal.acdb:system/etc/Hdmi_cal.acdb \
    $(LOCAL_PATH)/etc/hltrd.bin:system/etc/hltrd.bin \
    $(LOCAL_PATH)/etc/General_cal.acdb:system/etc/General_cal.acdb \
    $(LOCAL_PATH)/etc/Handset_cal.acdb:system/etc/Handset_cal.acdb \
    $(LOCAL_PATH)/etc/gps.conf:system/etc/gps.conf \
    $(LOCAL_PATH)/etc/hltof.bin:system/etc/hltof.bin
